// <auto-generated />
namespace Week14_DateNightProject_04122016.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddTitle30 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTitle30));
        
        string IMigrationMetadata.Id
        {
            get { return "201604142339110_AddTitle30"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
