// <auto-generated />
namespace Week14_DateNightProject_04122016.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddMultipleValidations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMultipleValidations));
        
        string IMigrationMetadata.Id
        {
            get { return "201604171730525_AddMultipleValidations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
